### ISSUE TITLE
Micropython 

### ISSUE THREAD

**Issue by bittu-digital** [ztachip/ztachip#24]
git clone https://github.com/micropython/micropython.git
cd micropython/ports
cp -avr <ztachip installation folder>/micropython/ztachip_port .
cd ztachip_port
export PATH=/opt/riscv/bin:$PATH
export ZTACHIP=<ztachip installation folder>
make clean
make

these are the commands which i followed to build ztachip as micropython port. But I got the error when i ran the last step i.e, make.
I donot know how to resolve this error. It will be very helpful on resolving this 
![image](https://github.com/user-attachments/assets/8318b844-2302-45a5-98af-fdb781cd79cc)

**Comment by ztachip** [comment]
Set below
export ZTACHIP=<Directory where ztachip is installed>
Note that ztachip must be built first before micropython build

**Comment by bittu-digital** [comment]
I have done the build process , standalone image is working fine.
While going with micro-python , 
export ZTACHIP=<given the path , where zta-chip is built>.
But the error i got is same again after "make"

Even while opening minicom using " sudo minicom -w -D /dev/ttyUSB1" i could not open any prompt to paste the example codes.

**Comment by ztachip** [comment]
You seem to run a different version of RISCV compiler.
Try to rebuild RISCV tool chain with instruction under section "Download and build RISCV tool chain"

**Comment by ztachip** [comment]
FPGA must be reset after you connect the serial port since it disrupts the JTAG connection of RISCV core.

**Comment by bittu-digital** [comment]
I downloaded the same RISCV tool chain which worked for the standalone image, and Also I did reset the FPGA. I got the same error.
Can you provide me the detailed process for micro-python, may be I am missing something.

**Comment by ztachip** [comment]
Tensorflow support is implemented under...
https://github.com/ztachip/ztachip/blob/master/SW/apps/nn/nn.cpp
The layer currenty supported are shown in function NeuralNet::CreateLayer which are the layers required for Mobitnet and SSD-Mobinet
If face detection uses these same layer types than it should work already. You can take a look at example in SW/src/vision_ai.cpp on how to load and run TensorFlow model.
Otherwise, you need to port the missing layers from TensorFlowLite to ztachip if the new layers are not taking much computing, otherwise, the new layers need an accelerated version using ztachip programming language.

**Comment by ztachip** [comment]
If you still have trouble with micropython build, please try latest version and copy over the new ztachip_port folder
